version: "3.0"
services:
    bits-for-ban-app:
        build: .
        volumes:
            - ${PWD}:/app
            - /app/node_modules
        env_file:
            - ./.env
        ports:
            - "3000:3000"
